sudo: false
language: java
cache:
  directories:
   - $HOME/.m2
   - $HOME/.cache/pip
   - $HOME/conda
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
   script: xvfb-run mvn verify -B
   before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
      bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
      fi
 - os: osx
   osx_image: xcode8.3
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
   before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
      bash Miniconda3-latest-MacOSX-x86_64.sh -f -b -p $HOME/conda;
      fi
    - export JAVA_HOME=$(/usr/libexec/java_home)
install:
 - source $HOME/conda/bin/activate root
 - conda install -y -q pandas protobuf
 - mvn package -B
