sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
   - $HOME/.m2
   - $HOME/.cache/pip
   - $HOME/conda
# Verify step requires pandas and protobuf Python packages
before_install:
  - if [ ! -e $HOME/conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh;
    bash Miniconda-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
    fi
  - source $HOME/conda/bin/activate root
  - conda install -y -q pandas protobuf
install: mvn package -B
script: xvfb-run mvn verify -B
