version: 1.0.{build}
cache: C:\Users\appveyor\.m2
environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
init:
- mvn --version
- "ECHO %PYTHON_VERSION% %MINICONDA%"
install:
- "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
- conda install -y -q -c conda-forge pandas protobuf
# KNIME defaults to python3 as executable, but conda only has python.exe, create python3 so tests can use it
- copy /Y %MINICONDA%\python.exe %MINICONDA%\python3.exe
build_script:
- cmd: mvn package -B
test_script:
- cmd: mvn verify -B
