version: 1.0.{build}
cache: C:\Users\appveyor\.m2
environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
init:
- mvn --version
- "ECHO %PYTHON_VERSION% %MINICONDA%"
install:
- "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
- conda install -y -q -c conda-forge pandas protobuf
build_script:
- cmd: mvn package -B
test_script:
- cmd: mvn verify -B
