#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} To trigger a Travis-CI build for every GitHub push or Pull Request:
${symbol_pound} 1. Goto https://travis-ci.org/profile/${github_organization}
${symbol_pound} 2. Flip the switch for the `${github_repository}` repo
sudo: false
language: java
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
   script: xvfb-run mvn verify -B
   before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh;
      bash Miniconda-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
      fi   
 - os: osx
   osx_image: xcode8.3
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
   before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
      bash Miniconda3-latest-MacOSX-x86_64.sh -f -b -p $HOME/conda;
      fi
    - export JAVA_HOME=$(/usr/libexec/java_home)
install:
 - source ${symbol_dollar}HOME/conda/bin/activate root
 - conda install -y -q pandas protobuf
 - pip install ${required_python_package}
 - mvn package -B
script: xvfb-run mvn verify -B
cache:
  directories:
   - ${symbol_dollar}HOME/.m2
   - ${symbol_dollar}HOME/.sonar/cache
   - ${symbol_dollar}HOME/.cache/pip
   - ${symbol_dollar}HOME/conda
${symbol_pound}${symbol_pound} Uncomment below to perform SonarCloud (https://sonarcloud.io/) analysis,
${symbol_pound}${symbol_pound} Next steps to have automated SonarCloud analysis reports for the repository:
${symbol_pound}${symbol_pound} 1. Create organization at https://sonarcloud.io/account/organizations with '${github_organization}' as name and '${github_organization.toLowerCase()}' as key
${symbol_pound}${symbol_pound} 2. Add SONAR_TOKEN env var to Travis-CI settings, a token can be generated at https://sonarcloud.io/account/security/
${symbol_pound}${symbol_pound} 3. Push a change to GitHub to trigger a Travis-CI build and SonarCloud analysis
${symbol_pound}after_success:
${symbol_pound}- mvn sonar:sonar -Dsonar.login=${symbol_dollar}SONAR_TOKEN
